#!/usr/bin/env bash
# Generate Diode OAuth credentials and wire local NetBox + agent config.
# NetBox/Postgres/Redis env files under dev/netbox/env/ are committed local
# demo defaults — this script does not regenerate them.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV="$ROOT/dev"
DIODE="$DEV/diode"
NETBOX_SECRETS="$DEV/netbox/secrets"
NETBOX_ENV="$DEV/netbox/env/netbox.env"

generate_secret() {
  # Enough entropy after base64 charset filtering.
  while true; do
    local s
    s="$(head -c 48 /dev/urandom | base64 | tr -d '/\n+=' | head -c 40)"
    if [[ ${#s} -eq 40 ]]; then
      printf '%s' "$s"
      return
    fi
  done
}

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi

mkdir -p "$DIODE/oauth2/client" "$NETBOX_SECRETS" "$DIODE/nginx"

# Ensure upstream Diode assets exist (compose + nginx).
if [[ ! -f "$DIODE/docker-compose.yaml" ]]; then
  echo "Missing $DIODE/docker-compose.yaml — re-run from a complete checkout." >&2
  exit 1
fi

if [[ ! -f "$NETBOX_ENV" ]]; then
  echo "Missing $NETBOX_ENV — expected committed local demo defaults." >&2
  exit 1
fi

# Prefer the committed NetBox SUPERUSER_API_TOKEN until create-netbox-token.sh mints a v1 token.
NB_SUPERUSER_API_TOKEN="$(grep -E '^SUPERUSER_API_TOKEN=' "$NETBOX_ENV" | cut -d= -f2- || true)"

CREDS="$DIODE/oauth2/client/client-credentials.json"
if [[ ! -f "$CREDS" ]]; then
  echo "Generating OAuth2 client credentials..."
  INGEST_SECRET="$(generate_secret)"
  TO_NETBOX_SECRET="$(generate_secret)"
  NETBOX_TO_DIODE_SECRET="$(generate_secret)"
  cat >"$CREDS" <<EOF
[
  {
    "client_id": "diode-ingest",
    "client_secret": "${INGEST_SECRET}",
    "grant_types": ["client_credentials"],
    "scope": "diode:ingest"
  },
  {
    "client_id": "diode-to-netbox",
    "client_secret": "${TO_NETBOX_SECRET}",
    "grant_types": ["client_credentials"],
    "scope": "netbox:read netbox:write"
  },
  {
    "client_id": "netbox-to-diode",
    "client_secret": "${NETBOX_TO_DIODE_SECRET}",
    "grant_types": ["client_credentials"],
    "scope": "diode:read diode:write"
  }
]
EOF
else
  echo "Using existing $CREDS"
  INGEST_SECRET="$(jq -r '.[] | select(.client_id=="diode-ingest") | .client_secret' "$CREDS")"
  TO_NETBOX_SECRET="$(jq -r '.[] | select(.client_id=="diode-to-netbox") | .client_secret' "$CREDS")"
  NETBOX_TO_DIODE_SECRET="$(jq -r '.[] | select(.client_id=="netbox-to-diode") | .client_secret' "$CREDS")"
fi

# Secret file consumed by the Diode NetBox plugin (default path).
printf '%s' "$NETBOX_TO_DIODE_SECRET" >"$NETBOX_SECRETS/netbox_to_diode"
chmod 600 "$NETBOX_SECRETS/netbox_to_diode"

# Diode server .env (same-network NetBox URL).
REDIS_PASSWORD="$(generate_secret)"
POSTGRES_PASSWORD="$(generate_secret)"
DIODE_PG_PASSWORD="$(generate_secret)"
HYDRA_PG_PASSWORD="$(generate_secret)"
HYDRA_SYSTEM_SECRET="$(generate_secret)"

cat >"$DIODE/.env" <<EOF
DIODE_NGINX_PORT=8080
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_HOST=redis
REDIS_PORT=6378
REDIS_USERNAME=
LOGGING_LEVEL=INFO
LOGGING_FORMAT=json
SENTRY_DSN=
MIGRATION_ENABLED=true
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DIODE_POSTGRES_DB_NAME=diode
DIODE_POSTGRES_USER=diode
DIODE_POSTGRES_PASSWORD=${DIODE_PG_PASSWORD}
TELEMETRY_ENVIRONMENT=dev
TELEMETRY_METRICS_EXPORTER=none
TELEMETRY_TRACES_EXPORTER=none
HYDRA_POSTGRES_DB_NAME=hydra
HYDRA_POSTGRES_USER=hydra
HYDRA_POSTGRES_PASSWORD=${HYDRA_PG_PASSWORD}
HYDRA_STRATEGIES_ACCESS_TOKEN=jwt
HYDRA_STRATEGIES_REFRESH_TOKEN=jwt
HYDRA_STRATEGIES_JWT_SCOPE_CLAIM=both
HYDRA_TTL_ACCESS_TOKEN=1h
HYDRA_OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public
HYDRA_URLS_SELF_ISSUER=http://hydra:4444
HYDRA_SECRETS_SYSTEM_0=${HYDRA_SYSTEM_SECRET}
AUTH_HTTP_PORT=8080
OAUTH2_PUBLIC_SERVER_URL=http://hydra:4444
OAUTH2_ADMIN_SERVER_URL=http://hydra:4445
DIODE_AUTH_TOKEN_URL=http://diode-auth:8080/token
DIODE_TO_NETBOX_CLIENT_ID=diode-to-netbox
DIODE_TO_NETBOX_CLIENT_SECRET=${TO_NETBOX_SECRET}
DIODE_TO_NETBOX_RATE_LIMITER_RPS=20
DIODE_TO_NETBOX_RATE_LIMITER_BURST=1
NETBOX_DIODE_PLUGIN_API_BASE_URL=http://netbox:8080/api/plugins/diode
NETBOX_DIODE_PLUGIN_API_TIMEOUT_SECONDS=30
NETBOX_DIODE_PLUGIN_SKIP_TLS_VERIFY=true
ENABLE_GRAPH_DB=false
INGESTION_LOG_PROCESSOR_BATCH_SIZE=50
INGESTION_LOG_PROCESSOR_CONCURRENCY=1
AUTO_APPLY_PROCESSOR_BATCH_SIZE=50
AUTO_APPLY_PROCESSOR_CONCURRENCY=1
EOF

# Env for host-side orb-agent / workspace.
cat >"$DEV/.env.local" <<EOF
# Generated by dev/setup.sh — do not commit
NETBOX_API_URL=http://localhost:8000
NETBOX_API_TOKEN=${NB_SUPERUSER_API_TOKEN}
DIODE_TARGET=grpc://localhost:8080/diode
DIODE_CLIENT_ID=diode-ingest
DIODE_CLIENT_SECRET=${INGEST_SECRET}
EOF
chmod 600 "$DEV/.env.local"

# Agent policy pointed at local Diode (host network / published ports).
cat >"$DEV/agent.local.yaml" <<EOF
# Generated local Orb Agent policy — Diode target is the compose-published port.
orb:
  config_manager:
    active: local
  backends:
    worker:
      common:
        diode:
          target: grpc://localhost:8080/diode
          client_id: \${DIODE_CLIENT_ID}
          client_secret: \${DIODE_CLIENT_SECRET}
          agent_name: platformone_local_1
          # dry_run: true
          # dry_run_output_dir: /opt/orb
  policies:
    worker:
      extreme_platformone_worker:
        config:
          package: orb_extreme_platformone
          # omit schedule to run once
          BOOTSTRAP: true
          NETBOX_API_URL: \${NETBOX_API_URL}
          NETBOX_API_TOKEN: \${NETBOX_API_TOKEN}
          PLATFORMONE_API_TOKEN: \${PLATFORMONE_API_TOKEN}
          classification: ALL
          name_source: hostname
        scope:
          sites: ["*"]
EOF

# workers.txt install path for a repo-root mount at /opt/orb
cat >"$DEV/workers.local.txt" <<EOF
.
EOF

cat <<EOF

Setup complete.

Next:
  export PATH="\$HOME/.local/bin:/home/linuxbrew/.linuxbrew/bin:\$PATH"
  docker compose -f "$DEV/docker-compose.yml" up -d --build
  # optional: omit the workspace service with:
  #   docker compose -f "$DEV/docker-compose.yml" up -d --build --scale workspace=0

NetBox:  http://localhost:8000  (admin / admin)
Diode:   grpc://localhost:8080/diode

After NetBox is healthy, create an API token for bootstrap:
  ./dev/create-netbox-token.sh

Credentials written to (gitignored):
  $DEV/.env.local
  $CREDS
  $DIODE/.env

NetBox compose env (committed local demo defaults): $DEV/netbox/env/*.env

Run the orb agent against this stack (from repo root):
  set -a; source "$DEV/.env.local"; set +a
  # also export PLATFORMONE_API_TOKEN=...
  docker run --rm --network host \\
    -v "\$PWD:/opt/orb/" \\
    -e INSTALL_WORKERS_PATH=/opt/orb/dev/workers.local.txt \\
    -e DIODE_CLIENT_ID -e DIODE_CLIENT_SECRET \\
    -e PLATFORMONE_API_TOKEN \\
    -e NETBOX_API_URL -e NETBOX_API_TOKEN \\
    netboxlabs/orb-agent:latest run -c /opt/orb/dev/agent.local.yaml
EOF
